name: "Run nixpkgs-review"
run-name: >-
  Review on ${{github.event.inputs.patch-repo}}:${{github.event.inputs.patch-ref}},
  based on ${{github.event.inputs.base-ref}}
on:
  workflow_dispatch:
    inputs:
      patch-repo:
        description: Patch repository
        required: true
        default: 'usertam/nixpkgs'
      patch-ref:
        description: Patch branch (or ref)
        required: true
        default: 'patch/'
      patch-depth:
        description: Patch branch fetch depth
        required: true
        default: 0
      base-ref:
        description: Base branch (or ref) in nixpkgs
        required: true
        default: 'master'
      base-depth:
        description: Base branch fetch depth
        required: true
        default: 0
      build-args:
        description: Build arguments to nixpkgs-review
        default: '--print-build-logs '
      nixpkgs-config:
        description: >-
          Custom nixpkgs configuration to nixpkgs-review, e.g.
          `allowBroken = true; allowUnfree = true;
          allowUnsupportedSystem = true;
          allowInsecurePredicate = x: true;`
      extra-args:
        description: Extra arguments to nixpkgs-review
jobs:
  review:
    name: Review on ${{matrix.system}}
    strategy:
      matrix:
        include:
        - system: x86_64-linux
          runs-on: ubuntu-latest
        - system: aarch64-linux
          runs-on: ubuntu-24.04-arm
        - system: x86_64-darwin
          runs-on: macos-13
        - system: aarch64-darwin
          runs-on: macos-latest
      fail-fast: false
    runs-on: ${{matrix.runs-on}}
    outputs:
      patch-commit: ${{steps.rev-parse.outputs.patch}}
      base-commit: ${{steps.rev-parse.outputs.base}}
    steps:
    - uses: actions/checkout@main
      with:
        repository: ${{github.event.inputs.patch-repo}}
        ref: ${{github.event.inputs.patch-ref}}
        fetch-depth: ${{github.event.inputs.patch-depth}}
    - uses: DeterminateSystems/nix-installer-action@main
    - name: Fetch upstream nixpkgs base
      run: |
        git remote add upstream https://github.com/NixOS/nixpkgs.git
        if [ "${{ github.event.inputs.base-depth }}" -gt 0 ]; then
          git fetch upstream ${{github.event.inputs.base-ref}} --depth=${{github.event.inputs.base-depth}}
        else
          git fetch upstream ${{github.event.inputs.base-ref}}
        fi
    - name: Output reference hashes
      id: rev-parse
      run: |
        echo "patch=$(git rev-parse --short ${{github.event.inputs.patch-ref}})" | tee -a $GITHUB_OUTPUT
        echo "base=$(git rev-parse --short upstream/${{github.event.inputs.base-ref}})" | tee -a $GITHUB_OUTPUT
    - name: Set up github-actions name and email
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Set up swap space
      uses: pierotofy/set-swap-space@master
      if: runner.os == 'Linux'
      with:
        swap-size-gb: 16
    - name: Run nixpkgs-review
      run: |
        echo 'nix run nixpkgs/nixpkgs-unstable#nixpkgs-review -- rev -b ${{github.event.inputs.base-ref}} HEAD \' | tee review.sh
        if [ -n "${{github.event.inputs.build-args}}" ]; then
          echo "  --build-args '${{github.event.inputs.build-args}}' \\" | tee -a review.sh
        fi
        if [ -n "${{github.event.inputs.nixpkgs-config}}" ]; then
          echo "  --extra-nixpkgs-config '{ ${{github.event.inputs.nixpkgs-config}} }' \\" | tee -a review.sh
        fi
        if [ -n "${{github.event.inputs.extra-args}}" ]; then
          echo "  ${{github.event.inputs.extra-args}} \\" | tee -a review.sh
        fi
        echo "  --print-result" | tee -a review.sh
        bash review.sh | tee ${{matrix.system}}.report.tmp
    - name: Report
      run: |
        grep -vE '\$ |HEAD is|Local eval' ${{matrix.system}}.report.tmp | \
          perl -e "print reverse(<>)" | sed -n '/<\/details>/,/## `nixpkgs-review` result/p' | perl -e "print reverse(<>)" > ${{matrix.system}}.report
        echo -n '::notice::%0A'
        sed 'H;1h;$!d;x;s/\n/%0A/g' ${{matrix.system}}.report
    - name: Upload review
      uses: actions/upload-artifact@main
      with:
        name: ${{matrix.system}}
        path: ${{matrix.system}}.report
  report:
    name: Report
    needs: review
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@main
      with:
        merge-multiple: true
    - name: Write summary report
      run: |
        sed -n '/## /,$p' x86_64-linux.report | sed '/---/d' | tee all.report
        if grep -q 'x86_64-linux' all.report; then
          echo | tee -a all.report;
        fi
        sed -n '/### /,$p' aarch64-linux.report | tee -a all.report
        if grep -q 'aarch64-linux' all.report; then
          echo | tee -a all.report;
        fi
        sed -n '/### /,$p' x86_64-darwin.report | tee -a all.report
        if grep -q 'x86_64-darwin' all.report; then
          echo | tee -a all.report;
        fi
        sed -n '/### /,$p' aarch64-darwin.report | tee -a all.report
        if ! grep -q '[^[:space:]]' all.report; then
          echo 'Nothing in the reports. Either no changes, or review crashed out :(' | tee all.report
          echo 'Try adding allow flags to `--extra-nixpkgs-config`?' | tee -a all.report
        fi
    - name: Display summary report
      run: |
        cat <<EOF > $GITHUB_STEP_SUMMARY
        ## Review configuration
        <table>
          <tr>
            <th></th>
            <th>Repository</th>
            <th>Branch/Reference</th>
            <th>Commit (rev-parse)</th>
            <th>Depth</th>
          </tr>
          <tr>
            <td>Patch</td>
            <td>${{github.event.inputs.patch-repo}}</td>
            <td>${{github.event.inputs.patch-ref}}</td>
            <td><code>${{needs.review.outputs.patch-commit}}</code></td>
            <td>${{github.event.inputs.patch-depth}}</td>
          </tr>
          <tr>
            <td>Base</td>
            <td>NixOS/nixpkgs</td>
            <td>${{github.event.inputs.base-ref}}</td>
            <td><code>${{needs.review.outputs.base-commit}}</code></td>
            <td>${{github.event.inputs.base-depth}}</td>
          </tr>
        </table>

        <table>
          <tr>
            <td>Build arguments</td>
            <td><code>${{github.event.inputs.build-args}}</code></td>
          </tr>
          <tr>
            <td>Nixpkgs config</td>
            <td><code>${{github.event.inputs.nixpkgs-config}}</code></td>
          </tr>
          <tr>
            <td>Extra arguments</td>
            <td><code>${{github.event.inputs.extra-args}}</code></td>
          </tr>
        </table>

        ### Rendered

        [\`usertam/nixpkgs-review-actions\`](${{github.server_url}}/usertam/nixpkgs-review-actions) [\`#${{github.run_id}}\`](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})

        $(cat all.report)

        ### Raw

        \`\`\`
        [\`usertam/nixpkgs-review-actions\`](${{github.server_url}}/usertam/nixpkgs-review-actions) [\`#${{github.run_id}}\`](${{github.server_url}}/${{github.repository}}/actions/runs/${{github.run_id}})

        $(cat all.report)
        \`\`\`
        EOF
